default_region       = "USWest2"
environment          = "dev"
app_name             = "httptrigger"
gh_token             = "SET AS ENV VARIABLE"
service_plan         = "api-appserviceplan-consumption"
storage_account_name = "storageaccount"